#!/usr/bin/env bash
# Deploy remit.md contracts to Base Sepolia testnet
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

echo "=== remit.md Testnet Deployment (Base Sepolia) ==="

# -- Validate env -----------------------------------------------------------
: "${DEPLOYER_PRIVATE_KEY:?Need DEPLOYER_PRIVATE_KEY}"
: "${BASE_SEPOLIA_RPC_URL:?Need BASE_SEPOLIA_RPC_URL}"
: "${FEE_RECIPIENT:?Need FEE_RECIPIENT (operator wallet address)}"

CHAIN_ID=84532   # Base Sepolia
ENV_OUT="$PROJECT_ROOT/.env.testnet"

# -- Deploy -----------------------------------------------------------------
cd "$PROJECT_ROOT/packages/contracts"

echo "→ Running forge script Deploy.s.sol on Base Sepolia..."
forge script script/Deploy.s.sol:Deploy \
  --rpc-url "$BASE_SEPOLIA_RPC_URL" \
  --private-key "$DEPLOYER_PRIVATE_KEY" \
  --broadcast \
  --verify \
  --verifier blockscout \
  --verifier-url https://base-sepolia.blockscout.com/api \
  --chain-id "$CHAIN_ID" \
  -vvv

# -- Extract deployed addresses from broadcast log --------------------------
BROADCAST_FILE="broadcast/Deploy.s.sol/$CHAIN_ID/run-latest.json"

if [[ ! -f "$BROADCAST_FILE" ]]; then
  echo "ERROR: Broadcast file not found: $BROADCAST_FILE"
  exit 1
fi

get_addr() {
  local contract=$1
  jq -r ".transactions[] | select(.contractName == \"$contract\") | .contractAddress" "$BROADCAST_FILE" | head -1
}

USDC_ADDR=$(get_addr "MockUSDC")
FEE_CALC_ADDR=$(get_addr "RemitFeeCalculator")
ROUTER_ADDR=$(get_addr "RemitRouter")
ESCROW_ADDR=$(get_addr "RemitEscrow")
TAB_ADDR=$(get_addr "RemitTab")
STREAM_ADDR=$(get_addr "RemitStream")
BOUNTY_ADDR=$(get_addr "RemitBounty")
DEPOSIT_ADDR=$(get_addr "RemitDeposit")

echo ""
echo "Deployed addresses:"
echo "  MockUSDC:           $USDC_ADDR"
echo "  RemitFeeCalculator: $FEE_CALC_ADDR"
echo "  RemitRouter:        $ROUTER_ADDR"
echo "  RemitEscrow:        $ESCROW_ADDR"
echo "  RemitTab:           $TAB_ADDR"
echo "  RemitStream:        $STREAM_ADDR"
echo "  RemitBounty:        $BOUNTY_ADDR"
echo "  RemitDeposit:       $DEPOSIT_ADDR"

# -- Write .env.testnet -------------------------------------------------------
cat > "$ENV_OUT" <<EOF
# remit.md testnet configuration (Base Sepolia)
# Auto-generated by scripts/deploy-testnet.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# DO NOT commit this file — add to .gitignore

CHAIN_ID=$CHAIN_ID
CHAIN_NAME=base-sepolia
RPC_URL=$BASE_SEPOLIA_RPC_URL

USDC_ADDRESS=$USDC_ADDR
FEE_CALCULATOR_ADDRESS=$FEE_CALC_ADDR
ROUTER_ADDRESS=$ROUTER_ADDR
ESCROW_ADDRESS=$ESCROW_ADDR
TAB_ADDRESS=$TAB_ADDR
STREAM_ADDRESS=$STREAM_ADDR
BOUNTY_ADDRESS=$BOUNTY_ADDR
DEPOSIT_ADDRESS=$DEPOSIT_ADDR

FEE_RECIPIENT=$FEE_RECIPIENT
EOF

echo ""
echo "→ Written: $ENV_OUT"
echo ""
echo "Next steps:"
echo "  1. Run: ./scripts/verify-contracts.sh"
echo "  2. Set REMITMD_TESTNET_ADDRESSES in your API server environment"
echo "  3. Run demo services: packages/demo-services/"
echo ""
echo "=== Deployment Complete ==="
